In [11]:
"""
    Given observations, find hidden state sequence by viterbi algorithm
"""
import numpy as np
from hmmlearn import hmm

states = ["London", "Barcelona", "Newyork"]
n_states = len(states)   # = 3

observations = ["Tuesday, ""Friday"]
n_observations = len(observations)

start_probability = np.array([0.1, 0.6, 0.3])

transition_probability = np.array([
  [0.10, 0.70, 0.20],
  [0.75, 0.15, 0.10],
  [0.60, 0.35, 0.05]
])

model = hmm.MultinomialHMM(n_components=n_states) 
X = [[0,0,1,0],[0,0,0,0],[0,0,0,1],[0,0,1,1]]
model.fit(X)
# MultinomialHMM: observation distribution in Multinomial
print(model.startprob_)
print(model.transmat_)

prob = model.decode(np.array([0,1,0,1]).reshape(4,1))
print(np.exp(prob[0]))


[0.41892496 0.5795886  0.00148644]
[[0.33054932 0.32912054 0.34033014]
 [0.33828766 0.33797772 0.32373462]
 [0.27817969 0.27033024 0.45149007]]
0.0048236554774752655
