In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [10]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Specias']
dataset = pd.read_csv("MTQ6.csv", names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width     Specias
0           5.1          3.5           1.4          0.2      setosa
1           4.9          3.0           1.4          0.2      setosa
2           6.6          2.9           4.6          1.3  versicolor
3           5.2          2.7           3.9          1.4  versicolor
4           6.9          3.1           5.1          2.3   virginica
5           5.8          2.7           5.1          1.9   virginica
6           7.0          3.2           4.7          1.4  versicolor
7           5.0          3.3           1.4          0.2      setosa
8           5.9          3.0           5.1          1.8   virginica

In [11]:
X = dataset.iloc[:, :-1].values         # Assign 1st/2nd/3rd/4th colums values to X
y = dataset.iloc[:, 4].values           # Assign 5th column values to y

In [21]:
#trainingset and test set split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)   # training set: 85%

In [22]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 1.12587994,  0.89221782,  0.66910211,  1.35066466],
       [-0.18764666,  0.32444284,  0.66910211,  0.5356084 ],
       [-1.50117325,  0.32444284, -2.31878489, -2.07257163],
       [ 0.73182196, -0.24333213,  0.26533359, -0.27944786],
       [ 1.2572326 ,  1.45999279,  0.3460873 , -0.11643661],
       [-0.31899932, -1.37888208,  0.66910211,  0.69861965],
       [-1.10711527, -1.37888208, -0.29994232, -0.11643661]])

In [26]:
#prediction
from sklearn.neighbors import KNeighborsClassifier

error = []
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
error.append(np.mean(y_pred != y_test))
print(error)

[0.0]


In [15]:
#evaluating algortim
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1 0 0]
 [0 0 0]
 [0 1 0]]


/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall 

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         1
  versicolor       0.00      0.00      0.00         0
   virginica       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2

