In [8]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [9]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Specias']
dataset = pd.read_csv("MTQ6.csv", names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width     Specias
0           5.1          3.5           1.4          0.2      setosa
1           4.9          3.0           1.4          0.2      setosa
2           6.6          2.9           4.6          1.3  versicolor
3           5.2          2.7           3.9          1.4  versicolor
4           6.9          3.1           5.1          2.3   virginica
5           5.8          2.7           5.1          1.9   virginica
6           7.0          3.2           4.7          1.4  versicolor
7           5.0          3.3           1.4          0.2      setosa
8           5.9          3.0           5.1          1.8   virginica

In [10]:
X = dataset.iloc[:, :-1].values         # Assign 1st/2nd/3rd/4th colums values to X
y = dataset.iloc[:, 4].values           # Assign 5th column values to y

In [11]:
#trainingset and test set split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)   # training set: 85%

In [12]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.76612047, -1.28097974,  0.10286215,  0.35303663],
       [ 1.64715901,  1.07871978,  0.62652403,  0.35303663],
       [-1.16833371,  0.13483997, -1.5335812 , -1.50040566],
       [ 0.03830602, -1.28097974,  0.88835496,  1.12530424],
       [ 1.11087468, -0.33709993,  0.56106629,  0.1985831 ],
       [ 0.17237711,  0.13483997,  0.88835496,  0.97085072],
       [-1.03426263,  1.55065968, -1.5335812 , -1.50040566]])

In [13]:
#prediction
from sklearn.neighbors import KNeighborsClassifier

error = []
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
error.append(np.mean(y_pred != y_test))
print(error)

[0.5]


In [14]:
#evaluating algortim
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1 0 0]
 [0 0 0]
 [0 1 0]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         1
  versicolor       0.00      0.00      0.00         0
   virginica       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2

